import React from 'react'
import ReportForm from "./ReportForm"

type Props = {}

export const metadata: Metadata = {
    title: "Report",
    description: "Generated by create next app",
};

export default function reportpage({}: Props) {
  return <ReportForm/>
}